[package]
name = "mathdefs"
version = "0.1.0"
edition = "2021"
description = "Definitions of some math operations and related traits (with implementations)"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
